#!/bin/bash

export TIMEWARRIORDB=~/Dropbox/tasks/timewarrior
TIMEW_OUTPUT=$(timew | egrep "Tracking ")

TASK=$(echo "${TIMEW_OUTPUT}" | sed 's/Tracking //')
if [[ "${TASK}" == "" ]]; then
    TASK="something"
fi

OUTPUT=""
if [[ "${TIMEW_OUTPUT}" != "" ]]; then
    OUTPUT="Doing: ${TASK} -"
fi

TIMEW_OUTPUT=$(timew day | egrep "Tracked " | sed 's/ *Tracked *//')
OUTPUT="${OUTPUT} ${TIMEW_OUTPUT}"

echo ${OUTPUT}
