syntax on
set nocompatible
set laststatus=2
set linebreak
set number
set expandtab
set tabstop=4
set guioptions=t
set autochdir
set autoindent
set nowrap
set hlsearch
set guifont=Hack\ 9
set wildmenu
set undofile
set undodir=/home/manu/.vimundo/
set so=5
ino jj <Esc> 

set wildignore+=*.a,*.o
set wildignore+=*.png,*.tga,*.tif,*.jpg
set wildignore+=*.blend*
set wildignore+=*.git
set wildignore+=*.swp,*.tmp

"-------------"
" Folding settings
set foldmethod=syntax
set foldnestmax=10
set nofoldenable
set foldlevel=1

" Used to setup Vundle
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

"-------------"
" Plugins
Plugin 'gmarik/vundle'
Plugin 'Shougo/vimproc.vim'

" Completion
Plugin 'Shougo/neocomplete.vim'
Plugin 'osyo-manga/vim-marching'

" Git stuff
Plugin 'tpope/vim-fugitive'

" Theme
Plugin 'altercation/vim-colors-solarized'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'majutsushi/tagbar'

" Usage
Plugin 'xolox/vim-session'
Plugin 'vim-scripts/a.vim'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'mbbill/undotree'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-vinegar'
Plugin 'airblade/vim-rooter'

" Code highlight / format
Plugin 'rhysd/vim-clang-format'
Plugin 'tikhomirov/vim-glsl'
Plugin 'w0rp/ale'
Plugin 'soramugi/auto-ctags.vim'

" Miscellaneous
Plugin 'xolox/vim-misc'
Plugin 'Konfekt/FastFold'

filetype plugin on

"-------------"
" Shortcuts
nnoremap <F5> :NERDTreeFocus<CR>
nnoremap <F6> :UndotreeToggle \| UndotreeFocus<CR>
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

"-------------"
" Theme
set background=dark
colorscheme solarized

"-------------"
" Vim-session
let g:session_autosave = 'no'
let g:session_autoload = 'no'
set sessionoptions-=buffers

"-------------"
" Rooter
let g:rooter_patterns = ['.git/']
let g:rooter_silent_chdir = 1
let g:rooter_manual_only = 0

"-------------"
" Latex related configuration
set grepprg=grep\ -nH\ $*i
let g:tex_flavor='latex'

"-------------"
" Airline
"let g:airline_section_warning=''
let g:airline_powerline_fonts=1
let g:airline#extensions#tagbar#enabled = 0
let g:airline#extensions#ale#enabled = 1
if has('gui_running')
    let g:airline_theme='solarized'
else
    let g:airline_theme='dark'
endif

"-------------"
" Tagbar
nmap <F8> :TagbarToggle<CR>
let g:tagbar_autoclose=0
set tags=./tags;/

" Open definition in another split (horizontal or vertical)
map <C-\> :split<CR>:exec("tag ".expand("<cword>"))<CR>
map <A-]> :vsp <CR>:exec("tag ".expand("<cword>"))<CR>

"-------------"
" auto-ctags.vim
let g:auto_ctags = 1
let g:auto_ctags_directory_list = ['.git']
let g:auto_ctags_tags_name = 'tags'

"-------------"
" a.vim
let g:alternateSearchPath = 'reg:#\<src\>$#include#,reg:#\<include\>$#src#'

"-------------"
" CtrlP
let g:ctrlp_working_path_mode = 'ra'

"-------------"
" vim-clang-format
let g:clang_format#style_options = {
    \ "BasedOnStyle" : "LLVM",
    \ "AlignTrailingComments" : "true",
    \ "AlwaysBreakTemplateDeclarations" : "true",
    \ "AlignAfterOpenBracket" : "DontAlign",
    \ "AllowShortFunctionsOnASingleLine" : "Inline",
    \ "BinPackArguments" : "false",
    \ "BinPackParameters" : "false",
    \ "BreakBeforeBraces" : "Allman",
    \ "ColumnLimit" : 180,
    \ "IndentWidth" : 4,
    \ "PointerAlignment" : "Left",
    \ "Standard" : "Cpp11",
    \ "TabWidth" : 4}
autocmd FileType c,cpp ClangFormatAutoDisable

"-------------"
" neocomplete
" Disable AutoComplPop.
let g:acp_enableAtStartup = 0
" Use neocomplete.
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#disable_auto_complete = 0
" Use smartcase.
let g:neocomplete#enable_smart_case = 1
" Set minimum syntax keyword length.
let g:neocomplete#sources#syntax#min_keyword_length = 4

" <CR>: close popup and save indent.
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function()
  return (pumvisible() ? "\<C-y>" : "" ) . "\<CR>"
  " For no inserting <CR> key.
  "return pumvisible() ? "\<C-y>" : "\<CR>"
endfunction
" <TAB>: completion
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"

autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

"-------------"
" ale
let g:ale_lint_on_text_changed = 'never'

"-------------"
" vim-marching
let g:marching_clang_command = "clang"
let g:marching#clang_command#options = {
\     "cpp" : "-std=gnu++14"
\ }
let g:marching_include_paths = [
\ "/usr/include",
\ "/usr/local/include"
\]
let g:marching_enable_neocomplete = 1

if !exists('g:neocomplete#force_omni_input_patterns')
  let g:neocomplete#force_omni_input_patterns = {}
endif

let g:neocomplete#force_omni_input_patterns.cpp = ''
"	\ '[^.[:digit:] *\t]\%(\.\|->\)\w*\|\h\w*::\w*'

set updatetime=200

"-------------"
" FastFold
nmap zuz <Plug>(FastFoldUpdate)
let g:fastfold_savehook = 1
let g:fastfold_fold_command_suffixes =  ['x','X','a','A','o','O','c','C']
let g:fastfold_fold_movement_commands = [']z', '[z', 'zj', 'zk']
