#!/bin/bash

if ! hash radeontop 2> /dev/null; then
    echo ""
    exit
fi

if [[ $(nvidia-smi | grep "Driver Version") == "" ]]; then
    echo ""
    exit
fi

NVIDIA=$(nvidia-smi)
USAGE=$(echo ${NVIDIA} | egrep -o '[0-9]+\% +Default' | egrep -o '[0-9]+')
FREE_MEM=$(echo ${NVIDIA} | egrep -o '[0-9]+MiB /' | sed 's!MiB /!!')
TOTAL_MEM=$(echo ${NVIDIA} | egrep -o '/ +[0-9]+MiB' | sed 's!/ *!!' | sed 's/MiB//')

# Launch Nvidia-settings
if [[ "${BLOCK_BUTTON}" == "3" ]]; then
    nvidia-settings &
fi

echo ${FREE_MEM}/${TOTAL_MEM}/${USAGE}%
