#!/bin/bash

if [[ "${BLOCK_BUTTON}" != "" ]]; then
    dbus-send --dest=ru.gentoo.KbddService /ru/gentoo/KbddService ru.gentoo.kbdd.next_layout && sleep 0.1 && pkill -RTMIN+1 i3blocks
fi

OUTPUT=$(${HOME}/.config/i3/xkblayout-state print %s)

echo ${OUTPUT}
