#!/bin/bash

if ! hash system76-power 2> /dev/null; then
    echo ""
    exit
fi

S76PROFILE=$(system76-power profile | egrep -o 'Power Profile: [a-zA-Z]+' | cut -d ':' -f 2)
PROFILE=$(echo ${S76PROFILE##*( )})

if [[ "$BLOCK_BUTTON" == "3" ]]; then
    if [[ "${PROFILE}" == "Battery" ]]; then
        system76-power profile balanced
    else
        system76-power profile battery
    fi
fi

echo "${PROFILE}"
