#!/bin/bash

PULSE_AUDIO_SINK=1

if [[ "${BLOCK_BUTTON}" == "4" ]]; then
    pactl set-sink-volume ${PULSE_AUDIO_SINK} +5% && pkill -RTMIN+10 i3blocks
elif [[ "${BLOCK_BUTTON}" == "5" ]]; then
    pactl set-sink-volume ${PULSE_AUDIO_SINK} -5% && pkill -RTMIN+10 i3blocks
elif [[ "${BLOCK_BUTTON}" == "1" ]]; then
    pactl set-sink-mute ${PULSE_AUDIO_SINK} toggle && pkill -RTMIN+10 i3blocks
elif [[ "${BLOCK_BUTTON}" == "3" ]]; then
    pavucontrol
fi

MUTE=$(amixer -c 1 -M -D pulse get Master | grep -o -E 'Playback.*\[on\]' | head -1)
if [[ "${MUTE}" != "" ]]; then
    OUTPUT=$(amixer -c 1 -M -D pulse get Master | grep -o -E [[:digit:]]+% | head -1)
else
    OUTPUT="---"
fi

echo ${OUTPUT}
